version: '3'

services:
  postgres:
    image: postgres:13.3
    container_name: quarkus_test
    environment:
      - POSTGRES_USER=quarkus_test
      - POSTGRES_PASSWORD=quarkus_test
      - POSTGRES_DB=quarkus_test
    #command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - 5432:5432
    networks: 
      - tasks-network

networks:
  tasks-network:
    driver: bridge